// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.0.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace IntegrationTestingLibraryForSqlServer.IntegrationTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ProcedureFeature : Xunit.IClassFixture<ProcedureFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Procedure.feature"
#line hidden
        
        public ProcedureFeature(ProcedureFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Procedure", "\tProcedure setup and tear down functions", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Procedure setup and verify")]
        [Xunit.TraitAttribute("FeatureTitle", "Procedure")]
        [Xunit.TraitAttribute("Description", "Procedure setup and verify")]
        [Xunit.TraitAttribute("Category", "db")]
        public virtual void ProcedureSetupAndVerify()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Procedure setup and verify", new string[] {
                        "db"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("there is a test database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Data Type",
                        "Size",
                        "Decimal Places",
                        "Direction"});
            table1.AddRow(new string[] {
                        "Id",
                        "int",
                        "",
                        "",
                        "Input"});
            table1.AddRow(new string[] {
                        "Name",
                        "nvarchar",
                        "50",
                        "",
                        "Input"});
            table1.AddRow(new string[] {
                        "Decimal1",
                        "decimal",
                        "10",
                        "5",
                        "Input"});
            table1.AddRow(new string[] {
                        "Decimal2",
                        "decimal",
                        "10",
                        "",
                        "Input"});
            table1.AddRow(new string[] {
                        "Decimal3",
                        "decimal",
                        "",
                        "",
                        "Input"});
#line 7
 testRunner.When("the procedure \"test\" is created with body \"return 0\"", ((string)(null)), table1, "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Data Type",
                        "Size",
                        "Decimal Places",
                        "Direction"});
            table2.AddRow(new string[] {
                        "Id",
                        "int",
                        "",
                        "",
                        "Input"});
            table2.AddRow(new string[] {
                        "Name",
                        "nvarchar",
                        "50",
                        "",
                        "Input"});
            table2.AddRow(new string[] {
                        "Decimal1",
                        "decimal",
                        "10",
                        "5",
                        "Input"});
            table2.AddRow(new string[] {
                        "Decimal2",
                        "decimal",
                        "10",
                        "0",
                        "Input"});
            table2.AddRow(new string[] {
                        "Decimal3",
                        "decimal",
                        "18",
                        "0",
                        "Input"});
#line 14
 testRunner.Then("the definition of procedure \"test\" should match", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Execute procedure and verify result")]
        [Xunit.TraitAttribute("FeatureTitle", "Procedure")]
        [Xunit.TraitAttribute("Description", "Execute procedure and verify result")]
        [Xunit.TraitAttribute("Category", "db")]
        public virtual void ExecuteProcedureAndVerifyResult()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Execute procedure and verify result", new string[] {
                        "db"});
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given("there is a test database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Data Type",
                        "Size",
                        "Decimal Places",
                        "Direction"});
            table3.AddRow(new string[] {
                        "Id",
                        "int",
                        "",
                        "",
                        "Input"});
            table3.AddRow(new string[] {
                        "Name",
                        "nvarchar",
                        "50",
                        "",
                        "Input"});
            table3.AddRow(new string[] {
                        "Decimal1",
                        "decimal",
                        "10",
                        "5",
                        "Input"});
            table3.AddRow(new string[] {
                        "Decimal2",
                        "decimal",
                        "10",
                        "",
                        "Input"});
            table3.AddRow(new string[] {
                        "Decimal3",
                        "decimal",
                        "",
                        "",
                        "Input"});
#line 25
 testRunner.And("the procedure \"test\" is created with body \"return 5\"", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Data Type",
                        "Size",
                        "Decimal Places",
                        "Direction",
                        "Value"});
            table4.AddRow(new string[] {
                        "Id",
                        "int",
                        "",
                        "",
                        "Input",
                        "1"});
            table4.AddRow(new string[] {
                        "Name",
                        "nvarchar",
                        "50",
                        "",
                        "Input",
                        "Test"});
            table4.AddRow(new string[] {
                        "Decimal1",
                        "decimal",
                        "10",
                        "5",
                        "Input",
                        "1.2"});
            table4.AddRow(new string[] {
                        "Decimal2",
                        "decimal",
                        "10",
                        "0",
                        "Input",
                        "1.2"});
            table4.AddRow(new string[] {
                        "Decimal3",
                        "decimal",
                        "18",
                        "0",
                        "Input",
                        "1.2"});
#line 32
 testRunner.When("the procedure \"test\" is executed", ((string)(null)), table4, "When ");
#line 39
 testRunner.Then("the return value should be 5", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ProcedureFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ProcedureFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
