// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34014
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace IntegrationTestingLibraryForSqlServer.IntegrationTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ProcedureFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Procedure.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Procedure", "Procedure setup and tear down functions", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Procedure")))
            {
                IntegrationTestingLibraryForSqlServer.IntegrationTests.ProcedureFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Procedure setup and verify")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Procedure")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("db")]
        public virtual void ProcedureSetupAndVerify()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Procedure setup and verify", new string[] {
                        "db"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("there is a test database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Data Type",
                        "Size",
                        "Precision",
                        "Direction"});
            table1.AddRow(new string[] {
                        "Id",
                        "int",
                        "",
                        "",
                        "Input"});
            table1.AddRow(new string[] {
                        "Name",
                        "nvarchar",
                        "50",
                        "",
                        "Input"});
#line 7
 testRunner.When("the procedure \"test\" is created with body \"return 0\"", ((string)(null)), table1, "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Data Type",
                        "Size",
                        "Precision",
                        "Direction"});
            table2.AddRow(new string[] {
                        "Id",
                        "int",
                        "",
                        "",
                        "Input"});
            table2.AddRow(new string[] {
                        "Name",
                        "nvarchar",
                        "50",
                        "",
                        "Input"});
#line 11
 testRunner.Then("the definition of procedure \"test\" should match", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Execute procedure and verify result")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Procedure")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("db")]
        public virtual void ExecuteProcedureAndVerifyResult()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Execute procedure and verify result", new string[] {
                        "db"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("there is a test database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Data Type",
                        "Size",
                        "Precision",
                        "Direction"});
            table3.AddRow(new string[] {
                        "Id",
                        "int",
                        "",
                        "",
                        "Input"});
            table3.AddRow(new string[] {
                        "Name",
                        "nvarchar",
                        "50",
                        "",
                        "Input"});
#line 19
 testRunner.And("the procedure \"test\" is created with body \"return 5\"", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Data Type",
                        "Size",
                        "Precision",
                        "Direction",
                        "Value"});
            table4.AddRow(new string[] {
                        "Id",
                        "int",
                        "",
                        "",
                        "Input",
                        "1"});
            table4.AddRow(new string[] {
                        "Name",
                        "nvarchar",
                        "50",
                        "",
                        "Input",
                        "Test"});
#line 23
 testRunner.When("the procedure \"test\" is executed", ((string)(null)), table4, "When ");
#line 27
 testRunner.Then("the return value should be 5", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
